- name: install Xcode
  ansible.builtin.shell: mas install 497799835

- name: disable live chnage input char with keybord
  community.general.osx_defaults:
    domain: com.apple.inputmethod.Kotoeri
    key: JIMPrefLiveConversionKey
    type: int
    value: 0
    state: present

- name: enable file extension
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true

- name: show dotfiles
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true

- name: show full path
  community.general.osx_defaults:
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: true

- name: interface dark
  community.general.osx_defaults:
    key: AppleInterfaceStyle
    type: string
    value: Dark

- name: dock big icon
  community.general.osx_defaults:
    domain: com.apple.dock
    key: magnification
    type: integer
    value: 1

