
- name: homebrew update
  community.general.homebrew:
    update_homebrew: yes

- name: homebrew tap
  community.general.homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items:
    - homebrew/cask-versions
    - homebrew/core
    - weaveworks/tap

- name: homebrew cask packages install
  community.general.homebrew_cask:
    name: '{{ item }}'
    state: installed
  # GUI install to `/Application`
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
  with_items:
    - amazon-workspaces
    - boostnote
    - dash
    - datagrip
    - docker # should be setup after installing
#      - google-chrome
    - google-chrome-canary
    - google-cloud-sdk
    - google-japanese-ime
    - iterm2
    - keybase
    - remote-desktop-manager # microsoft remote desktop
    - postman
    - sequel-pro
    - skype
    - slack
    - sourcetree
    - visual-studio-code
    - zoom
    - biscuit
    - alfred
    - sublime-text
    - tor-browser

- name: homebrew packages install
  community.general.homebrew:
    name: '{{ item }}'
    state: '{{ item.state | default("present") }}'
  with_items:
    - amazon-ecs-cli
    - awscli
    - awsebcli
    - bash
    - bash-completion@2 # bash 4 <=
    - docker
    - gcc
    - gitlab-runner
    - go
    - helmfile
    - iproute2mac
    - jq
    - kubernetes-helm
    - kustomize
    - kubectx
    - lua
    - mas
    - mysql@5.6
    - nmap
    - nodebrew
    - packer
    - pdfcrack
    - pwgen
    - python3
    - redis
    - terraform
    - the_silver_searcher
    - tig
    - tree
    - watch
    - weaveworks/tap/eksctl
    - wget
    - yarn
    - rust
    - cowsay
    - lastpass-cli
    - zsh
    - tmux
    - aws-elasticbeanstalk
    - pyenv
    - oath-toolkit
    - pstree
    - bat
    - pv
    - git # also be installed git-completion
    - asdf
    - aws-sam-cli
