
- name: homebrew update
  community.general.homebrew:
    update_homebrew: yes

- name: homebrew tap
  community.general.homebrew_tap:
    name: '{{ item }}'
    state: present
  loop:
    - weaveworks/tap

- name: homebrew cask packages install
  community.general.homebrew_cask:
    name: '{{ item }}'
    state: latest
  loop:
    - amazon-workspaces
    - brave-browser
    - datagrip
    - docker # should be setup after installing
    - firefox
    - firefox@developer-edition
    - google-chrome@canary
    - google-chrome@dev
    - google-japanese-ime
    - iterm2
    - itsycal
    - keybase
    - postman
    - remote-desktop-manager # microsoft remote desktop
    - sequel-ace
    - slack
    - sublime-text
    - visual-studio-code
    - zoom
    # - alfred
    # - biscuit
    # - boostnote
    # - dash
    # - google-chrome
    # - google-cloud-sdk
    # - skype
    # - sourcetree
    # - tor-browser
    # - warp # terminal

- name: homebrew packages install
  community.general.homebrew:
    name: '{{ item }}'
    state: latest
  loop:
    - amazon-ecs-cli
    - asdf
    - aws-sam-cli
    - awscli
    - bash
    - bash-completion@2 # bash 4 <=
    - docker
    - gcc
    - git # also be installed git-completion
    - go
    - helmfile
    - iproute2mac
    - jq
    - kitty
    - kubectx
    - kubernetes-helm
    - kustomize
    - mas
    - nmap
    - nodebrew
    - pstree
    - pwgen
    - pyenv
    - redis
    - rust
    - tmux
    - tree
    - watch
    - weaveworks/tap/eksctl
    - yarn
    - zsh-autosuggestions
    # - aws-elasticbeanstalk
    # - awsebcli
    # - bat
    # - cowsay
    # - gitlab-runner
    # - lastpass-cli
    # - lua
    # - mysql@5.6
    # - oath-toolkit
    # - packer
    # - pdfcrack
    # - pv
    # - python3
    # - starship
    # - terraform
    # - the_silver_searcher
    # - tig
    # - wget
    # - zsh

- name: Run nodebrew setup_dirs
  command: /opt/homebrew/opt/nodebrew/bin/nodebrew setup_dirs
